spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ustinian-ai-builderx
    username: root
    password: 5201314WZH
#上面的配置是数据库连接信息，本项目中还用于代码生成器的使用，已确认可用
  application:
    name: ustinian-ai-builderx-backend
server:
  port: 8123
  servlet:
      context-path: /api
# springdoc-openapi????
springdoc:
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.ustinian.ustinianaibuilderx.controller
# knife4j???????????????
knife4j:
  enable: true
  setting:
    language: zh_cn